openapi: "3.0.0"
info:
  version: 1.0.0
  title: Kenta's Joke API
  description: A simple API to tell jokes
  contact:
    name: Kenta420
    email: poomipat002@gmial.com
    url: https://github.com/Poomipat-Ch
  servers:
    - url: http://{hostname}/api
      variables:
        hostname:
          default: localhost
  security:
    - bearerAuth: []
  paths:
    /joke:
      get:
        summary: Get a random joke
        operationId: getJoke
        tags:
          - joke
        responses:
          "200":
            description: OK
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Joke"
  components:
    securitySchemes:
      bearerAuth:
        type: http
        scheme: bearer
        bearerFormat: JWT
    schemas:
      User:
        type: object
        required:
          - displayName
          - balance
          - role
        properties:
          displayName:
            type: string
          balance:
            type: integer
          role:
            type: string

      Error:
        type: object
        required:
          - slug
          - message
        properties:
          slug:
            type: string
          message:
            type: string
